#UPDATED COMPLETELY FOR MICROBOONE
default: &default
  data_root: /scratch/midway3/hhall5/BNB_All_NoWire_00.h5
  checkpoint_dir: /scratch/midway3/hhall5/checkpoints/pid_microboone
  log_file_name: pid_training.log
  
  batch_size: 2
  valid_batch_size: 2
  limit_data: true
  limit_size: 1000
  num_data_workers: 1
  log_to_screen: true
  max_epochs: 100
  
  max_lr: 0.0001
  min_lr: 0.00001
  warmup_steps: 20
  total_steps: 5000
  
  embed_dim: 128
  embed_method: add
  pe_method: nerf
  klen: 30
  
  num_embedder_layers: 1
  use_attention_head: false
  continue_from_best: false
  
  loss_reweight: false
  rep_aaai: false
  save_checkpoint: true
  grad_clip_value: 0.1

mamba_microboone_pid:
  <<: *default
  num_layers_backbone: 6
  d_state: 16
  dropout: 0.1
  mambaversion: mamba1
  task: pid
  num_output_classes: 8
  pretrained_ckpt: /scratch/midway3/hhall5/checkpoints/mamba_microboone/00/training_checkpoints/ckpt.tar
